spring:
  application:
    name: MTR_CUSTOMER
  datasource:
    url: jdbc:postgresql://database-mtr.cd0cmocg8b24.ap-south-1.rds.amazonaws.com:5432/mtrapp
    username: postgres
    password: 2lolhyFpNac8oFglWcjl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true