spring:
  application:
    name: MTR_CUSTOMER
  datasource:
    url: jdbc:postgresql://database-mtr-app.cd0cmocg8b24.ap-south-1.rds.amazonaws.com:5432/database-mtr-app
    username: postgres
    password: vZG3NizPVcQ1lBkfRBXY
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true