name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main   # Run workflow only on this branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "MTR-Customer-Backend-Spring-Boot"
          environment_name: "MTR-Customer-Backend-Spring-Boot-env"
          version_label: "v-${{ github.sha }}"
          region: "ap-south-1"
          deployment_package: target/MTR_CUSTOMER-0.0.1-SNAPSHOT.jar
